version: '3'

services:
  # API service
  api:
    image: langgenius/dify-api:0.8.0
    restart: always
    environment:
      MODE: api
      CONSOLE_API_URL: ${CONSOLE_API_URL}
      CONSOLE_WEB_URL: ${CONSOLE_WEB_URL}
      SERVICE_API_URL: ${SERVICE_API_URL}
      APP_API_URL: ${APP_API_URL}
      APP_WEB_URL: ${APP_WEB_URL}
      SECRET_KEY: ${SECRET_KEY}
      INIT_PASSWORD: ${INIT_PASSWORD}
      WEB_API_CORS_ALLOW_ORIGINS: ${WEB_API_CORS_ALLOW_ORIGINS}
      CONSOLE_CORS_ALLOW_ORIGINS: ${CONSOLE_CORS_ALLOW_ORIGINS}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-difyai123456}
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-dify}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-difyai123456}
      VECTOR_STORE: weaviate
      WEAVIATE_ENDPOINT: http://weaviate:8080
      WEAVIATE_API_KEY: ${WEAVIATE_API_KEY:-WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih}
    depends_on:
      - db
      - redis
      - weaviate
    volumes:
      - ./volumes/app/storage:/app/api/storage
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dify-api.rule=Host(`dify.api.kodescraft.com`) || Host(`dify.console.api.kodescraft.com`)"
      - "traefik.http.services.dify-api.loadbalancer.server.port=5001"
      - "traefik.http.routers.dify-api.middlewares=cors-headers"
      - "traefik.http.routers.dify-api.entrypoints=https"
      - "traefik.http.routers.dify-api.tls=true"

  # Frontend web application
  web:
    image: langgenius/dify-web:0.8.0
    restart: always
    environment:
      CONSOLE_API_URL: ${CONSOLE_API_URL}
      APP_API_URL: ${APP_API_URL}
      SENTRY_DSN: ${WEB_SENTRY_DSN:-}
      NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED:-0}
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dify-web.rule=Host(`dify.kodescraft.com`)"
      - "traefik.http.services.dify-web.loadbalancer.server.port=3000"
      - "traefik.http.routers.dify-web.middlewares=cors-headers"
      - "traefik.http.routers.dify-web.entrypoints=https"
      - "traefik.http.routers.dify-web.tls=true"

  # ... (other services remain the same)

networks:
  coolify:
    external: true
